### ISSUE TITLE
Slate Editor

### ISSUE THREAD

**Issue by xiaoniuniu89** [codu-code/codu#321]
## Context

There is a first draft of the rich text editor. This is an issue to track all of the child issues of the text editor.

The editor is built using plate js which is a JavaScript library that extends Slate.js.
Slate.js is a framework for building rich text editors in browsers.
Plate.js adds extra features and utilities to simplify development like OOTB plugins.
It provides a higher-level API and additional abstractions on top of Slate.js and makes development a bit easier.

You can find the documentation here: [plate editor](https://plate.udecode.io/docs/)

The Editor uses an array of json data to describe what should be rendered as you type for example:

`{
  "type": "paragraph",
  "children": [
    {
      "text": "Hello Codu"
    }
  ]
}
`

everything is a plugin here. p tags, code blocks, iframes etc. There are some custom plugins inside components/SlateEditor/customPlugins.

You can create the business logic for the plugin here. 

You can override some styling here or in Editor/Settings/Plateui for how things are rendered in the editor.

What you type will serialized to html using [slate serializers](https://github.com/thompsonsj/slate-serializers). the rules for how it changes the json object to html can be found in Config/slateToHtml.

The html is sanitised using [dom purify](https://github.com/cure53/DOMPurify) and the config for that is currently inline when calling dom purify in the SlateEditor.tsx

html string is saved to database

the html string is parsed to html using [html-react-parser](https://github.com/remarkablemark/html-react-parser)

the html is serialized to a json object for slate to use using [slate serializers](https://github.com/thompsonsj/slate-serializers).the config for that is in Config/htmlToSlate

```[tasklist]
### Tasks
- [ ] https://github.com/codu-code/codu/issues/320
- [ ] https://github.com/codu-code/codu/issues/322
- [ ] https://github.com/codu-code/codu/issues/323
- [ ] https://github.com/codu-code/codu/issues/324
- [ ] Responsivness
- [ ] https://github.com/codu-code/codu/issues/325
- [ ] https://github.com/codu-code/codu/issues/327
- [ ] https://github.com/codu-code/codu/issues/326
- [ ] https://github.com/codu-code/codu/issues/328
- [ ] https://github.com/codu-code/codu/issues/329
```

**Comment by xiaoniuniu89** [comment]
@NiallJoeMaher is it nicer to have branch for this? merge into develop later?
