### ISSUE TITLE
Add light/dark mode for all pages.

### ISSUE THREAD

**Issue by NiallJoeMaher** [codu-code/codu#63]
I would love to have a toggle feature like this Tailwind demo: https://syntax.tailwindui.com/

- Should use the system settings by default
- Use the `dark:` class to make it easier to control/update
- We probably need a Theme wrapper for the application to make sure we can control it.
```[tasklist]
### Tasks
- [ ] https://github.com/codu-code/codu/issues/432
- [ ] https://github.com/codu-code/codu/issues/433
- [ ] https://github.com/codu-code/codu/issues/434
- [ ] https://github.com/codu-code/codu/issues/435
- [ ] https://github.com/codu-code/codu/issues/436
- [ ] https://github.com/codu-code/codu/issues/437
```

**Comment by tokyo3001** [comment]
@NiallJoeMaher Can you assign me this issue?

**Comment by pkspyder007** [comment]
@tokyo3001 sure you can pick it up

**Comment by jh3y** [comment]
Has there been some progress on this @tokyo3001?

**Comment by patrickhladun** [comment]
@jh3y @tokyo3001 is there any progress on this issue?

**Comment by NiallJoeMaher** [comment]
If I get no updates today I will assign it to you @patrickhladun

**Comment by sonngdev** [comment]
I can pick up this issue if it is important now and no one is doing it.

**Comment by NiallJoeMaher** [comment]
There isn't anyone working on this yet. As you see it's been open since October. It's a nice to have as it doesn't impact functionality thankfully. If you want to tackle it I'd be happy to assign it you!

**Comment by sonngdev** [comment]
I asked because this is the only issue with the `Help wanted` tag 😄 I don't mind taking it for now and joining more urgent issues in the future. 

By the way, since this issue is heavily related to UI, do we have any UI design documentation/Figma file? If not, I can also come up with my version of dark/light UI then we can iterate from that.

**Comment by NiallJoeMaher** [comment]
We had some light/dark mode pages earlier so I need to dig out some designs. Let's put this on hold until I have some designs for you or else we could end up in an endless back and forth 😹

**Comment by DarrachBarneveld** [comment]
Would like to assist if not parked?

**Comment by NiallJoeMaher** [comment]
Not parked! I'll link you the designs and some context etc. later or tomorrow. I'm about to jump on a flight. Because we can split this into multiple tasks.

**Comment by NiallJoeMaher** [comment]
I found it!

https://www.figma.com/file/yKc7ind3lHUTpqkjTePy1N/codu.co?type=design&node-id=107%3A164&mode=design&t=DyfBx9s5qMItxEPZ-1

![Light mode](https://github.com/codu-code/codu/assets/12615742/b952427c-335a-4fe3-903f-0e503e64b4fd)

I'm going to make a task list and we can start getting this done for Hacktoberfest! 🪂

**Comment by NiallJoeMaher** [comment]
@DarrachBarneveld the task list is here now: https://github.com/codu-code/codu/issues/63#issue-1400957466

**Comment by pateldivyesh1323** [comment]
@NiallJoeMaher Is there any task which will tackle light/dark mode  for header and footer?

**Comment by NiallJoeMaher** [comment]
@pateldivyesh1323 great thinking! I think there is a few tasks you've made me think of. 

- The pop up menus (having the appropriate dark mode)
- The footer #462 (leave a comment so I can assign it to you)
- The sidebar features (screenshot below):
![Screenshot 2023-10-02 at 08 01 32](https://github.com/codu-code/codu/assets/12615742/71ecc913-fbe4-473f-b984-1b86941d517c)

**Comment by pateldivyesh1323** [comment]
@NiallJoeMaher 
- Support Us Page :  Does not have dark mode 
- Getting Started, Your Posts, Profile Settings, Saved Posts : Does not have Light mode
